# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '../Qt_Ui/Login.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class LogIn_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(830, 652)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.Login = QtWidgets.QLabel(self.centralwidget)
        self.Login.setGeometry(QtCore.QRect(190, 40, 421, 581))
        font = QtGui.QFont()
        font.setFamily(".Savoye LET CC.")
        font.setPointSize(18)
        self.Login.setFont(font)
        self.Login.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.Login.setStyleSheet("border-image: url(:/bgImg/sunset.jpeg);\n"
"border-top-left-radius:40px;\n"
"border-bottom-left-radius:40px;\n"
"border-top-right-radius:40px;\n"
"border-bottom-right-radius:40px;")
        self.Login.setText("")
        self.Login.setObjectName("Login")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(320, 440, 161, 61))
        font = QtGui.QFont()
        font.setFamily("Optima")
        font.setPointSize(24)
        self.pushButton.setFont(font)
        self.pushButton.setStyleSheet("border-radius:8px;\n"
"color:white;\n"
"background: rgba(172,100,41,90%);\n"
"")
        self.pushButton.setObjectName("pushButton")
        self.Title = QtWidgets.QLabel(self.centralwidget)
        self.Title.setGeometry(QtCore.QRect(330, 70, 201, 81))
        font = QtGui.QFont()
        font.setFamily("Didot")
        font.setPointSize(51)
        self.Title.setFont(font)
        self.Title.setStyleSheet("color:white;")
        self.Title.setObjectName("Title")
        self.warning = QtWidgets.QLabel(self.centralwidget)
        self.warning.setGeometry(QtCore.QRect(300, 550, 250, 21))
        font = QtGui.QFont()
        font.setFamily(".New York")
        font.setPointSize(17)
        self.warning.setFont(font)
        self.warning.setStyleSheet("color:yellow;")
        self.warning.setOpenExternalLinks(False)
        self.warning.setObjectName("warning")
        self.PassWord = QtWidgets.QLineEdit(self.centralwidget)
        self.PassWord.setGeometry(QtCore.QRect(330, 340, 141, 41))
        font = QtGui.QFont()
        font.setPointSize(24)
        self.PassWord.setFont(font)
        self.PassWord.setStyleSheet("border-radius:8px;\n"
"background: rgba(255,255,255,50%);")
        self.PassWord.setEchoMode(QtWidgets.QLineEdit.Password)
        self.PassWord.setObjectName("PassWord")
        self.Account = QtWidgets.QLineEdit(self.centralwidget)
        self.Account.setGeometry(QtCore.QRect(330, 220, 141, 41))
        font = QtGui.QFont()
        font.setPointSize(24)
        self.Account.setFont(font)
        self.Account.setStyleSheet("border-radius:8px;\n"
"background: rgba(255,255,255,50%);")
        self.Account.setEchoMode(QtWidgets.QLineEdit.Normal)
        self.Account.setObjectName("Account")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.pushButton.setText(_translate("MainWindow", "Connect"))
        self.Title.setText(_translate("MainWindow", "Login"))
        self.warning.setText(_translate("MainWindow", ""))
        self.PassWord.setPlaceholderText(_translate("MainWindow", "   PassWord"))
        self.Account.setPlaceholderText(_translate("MainWindow", "           ID"))
from View import login_rc


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = LogIn_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
